<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>com.ferbo.bitacora</groupId>
  <artifactId>ferbo-bitacora</artifactId>
  <packaging>jar</packaging>
  <version>1.0.0-RELEASE</version>

  <name>ferbo-bitacora</name>
  <description>Bitácora operativa para el registro y seguimiento de los eventos que ocurren dentro del ecosistema de la empresa.</description>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    
    <!-- Java -->
    <java.version>1.8</java.version>

    <!-- Plugins -->
    <maven.compiler.plugin.version>3.11.0</maven.compiler.plugin.version>
    <maven.surefire.plugin.version>3.2.5</maven.surefire.plugin.version>

    <!-- JUnit 5 -->
    <junit.jupiter.version>5.10.0</junit.jupiter.version>

    <!-- JPA -->
    <javax.persistence.version>2.2</javax.persistence.version>

    <!-- Hibernate -->
    <hibernate.version>5.6.15.Final</hibernate.version>
  </properties>

  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>org.junit</groupId>
        <artifactId>junit-bom</artifactId>
        <version>5.11.0</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>

  <dependencies>
     <!-- Motor de ejecución de JUnit 5 -->
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-engine</artifactId>
            <version>${junit.jupiter.version}</version>
            <scope>test</scope>
        </dependency>

        <!-- (Opcional) Para ejecutar tests antiguos de JUnit 4 dentro de JUnit 5 -->
        <dependency>
            <groupId>org.junit.vintage</groupId>
            <artifactId>junit-vintage-engine</artifactId>
            <version>${junit.jupiter.version}</version>
            <scope>test</scope>
        </dependency>

        <dependency>
          <groupId>javax.persistence</groupId>
          <artifactId>javax.persistence-api</artifactId>
          <version>${javax.persistence.version}</version>
        </dependency>

        <dependency>
          <groupId>org.hibernate</groupId>
          <artifactId>hibernate-core</artifactId>
          <version>${hibernate.version}</version>
        </dependency>

  </dependencies>

  <build>
    <plugins>
     <!-- Compilación Java -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>${maven.compiler.plugin.version}</version>
                <configuration>
                    <source>${java.version}</source>
                    <target>${java.version}</target>
                </configuration>
            </plugin>

            <!-- Ejecución de tests -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>${maven.surefire.plugin.version}</version>
                <configuration>
                    <!-- Necesario para ejecutar JUnit 5 en Java 8 -->
                    <useModulePath>false</useModulePath>
                </configuration>
            </plugin>
    </plugins>
  </build>

  <distributionManagement>
		<repository>
			<id>github</id>
			<name>GitHub eabadillom Apache Maven Packages</name>
			<url>https://maven.pkg.github.com/eabadillom/ferbo-bitacora</url>
		</repository>
	</distributionManagement>

</project>
